spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/Proj1_DB_2021202078
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: always
logging:
  level:
    org.hibernate.type: trace